// <auto-generated />
namespace Simulador.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InicialV15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicialV15));
        
        string IMigrationMetadata.Id
        {
            get { return "202309111423263_InicialV15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
